### ISSUE TITLE
How to train my own datasets (format is like coco datasets)

### ISSUE THREAD

**Issue by EDG-Zola** [tianzhi0549/FCOS#54]
Now I have converted my datasets format to coco format, andI want to train my own datasets using FCOS. I referenced [GETTING_STARTED.md in mmdetection repo](https://github.com/open-mmlab/mmdetection/blob/master/GETTING_STARTED.md), and there is a tutorial in mmdetection repo to train my own datasets. But in FCOS repo, I find the file **FCOS/maskrcnn_benchmark/data/datasets/coco.py** is different like **/mmdetection/mmdet/datasets/coco.py**.  Is there any suggestions?

**Comment by tianzhi0549** [comment]
@EDG-Zola You do not need to change this code.
In order to train FCOS on your own dataset, you need to,

1. Add you dataset to https://github.com/tianzhi0549/FCOS/blob/master/maskrcnn_benchmark/config/defaults.py. Please use `_coco_style` as the suffix of your dataset names.
2. In https://github.com/tianzhi0549/FCOS/blob/master/configs/fcos/fcos_R_50_FPN_1x.yaml, change `DATASETS` to your own ones.
3. Modify `MODEL.FCOS.NUM_CLASSES` in https://github.com/tianzhi0549/FCOS/blob/ff8376bb903fe11a371df658f4bc87d3d6903125/maskrcnn_benchmark/config/defaults.py#L284 if your dataset has a different number of classes.

**Comment by sunpeng981712364** [comment]
Thanks for great works! just a refered question. If I have 29 classes,  _C.MODEL.FCOS.NUM_CLASSES should be set to 30?

**Comment by sunpeng981712364** [comment]
> @EDG-Zola You do not need to change this code.
> In order to train FCOS on your own dataset, you need to,
> 
> 1. Add you dataset to https://github.com/tianzhi0549/FCOS/blob/master/maskrcnn_benchmark/config/defaults.py. Please use `_coco_style` as the suffix of your dataset names.
> 2. In https://github.com/tianzhi0549/FCOS/blob/master/configs/fcos/fcos_R_50_FPN_1x.yaml, change `DATASETS` to your own ones.
> 3. Modify `MODEL.FCOS.NUM_CLASSES` in https://github.com/tianzhi0549/FCOS/blob/ff8376bb903fe11a371df658f4bc87d3d6903125/maskrcnn_benchmark/config/defaults.py#L284
>     if your dataset has a different number of classes.
Thanks for great works! just a refered question. If I have 29 classes, _C.MODEL.FCOS.NUM_CLASSES should be set to 30?

**Comment by tianzhi0549** [comment]
@sunpeng981712364 If the 29 classes do not contain the background class, `NUM_CLASSES` should be set as 30.

**Comment by sunpeng981712364** [comment]
hi,  I use fcos_demo.py to visualize the result and it seems right, But when I predict use  tools/testnet.py with coco protocol, all the AP/AR is close to zero.   Do I need to change  tools/testnet.py

**Comment by tianzhi0549** [comment]
@sunpeng981712364 I am not sure what is wrong with your code. It might be helpful to debug your code line by line.

**Comment by sunpeng981712364** [comment]
> @sunpeng981712364 谢谢大佬您的及时回复(#^.^#)

**Comment by sunpeng981712364** [comment]
@tianzhi0549 谢谢您的及时回复(#^.^#)嘻嘻

**Comment by liuguanglyc** [comment]
Can one or two 1080Ti GPU be used to train?

**Comment by tianzhi0549** [comment]
@liuguanglyc I think you can, but maybe you need to use a smaller input size (e.g., 600px).

**Comment by heng2j** [comment]
Hi @tianzhi0549 , I am trying to train with my own dataset with fcos_R_101_FPN_2x. 

However, I encountered the error that mentioned

RuntimeError: Error(s) in loading state_dict for GeneralizedRCNN:
        size mismatch for rpn.head.cls_logits.weight: copying a param with shape torch.Size([80, 256, 3, 3]) from checkpoint, the shape in current model is torch.Size([1, 256, 3, 3]).
        size mismatch for rpn.head.cls_logits.bias: copying a param with shape torch.Size([80]) from checkpoint, the shape in current model is torch.Size([11]).

I also removed all the previous checkpoints from ~/.torch/models/

Would you please advice on the steps to retrain a model with your own coco style dataset? Thank you so much!


**Training Command**
```
python -m torch.distributed.launch \
    --nproc_per_node=3 \
    --master_port=$((RANDOM + 10000)) \
    tools/train_net.py \
    --skip-test \
    --config-file configs/fcos/fcos_R_101_FPN_2x.yaml \
    DATALOADER.NUM_WORKERS 2 \
    OUTPUT_DIR training_dir/fcos_R_101_FPN_2x
```


**fcos_R_101_FPN_2x.yaml**
```
MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "../FCOS/FCOS_R_101_FPN_2x.pth"
  RPN_ONLY: True
  FCOS_ON: True
  BACKBONE:
    CONV_BODY: "R-101-FPN-RETINANET"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  RETINANET:
    USE_C5: False # FCOS uses P5 instead of C5
DATASETS:
  TRAIN: ("my_data_train_coco_style", "my_data_val_coco_style")
  TEST: ("my_data_test_coco_style",)
INPUT:
  MIN_SIZE_RANGE_TRAIN: (640, 800)
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1333
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.0001
  STEPS: (120000, 160000)
  MAX_ITER: 180000
  IMS_PER_BATCH: 4
  WARMUP_METHOD: "constant"
```
